import { DataTypes } from "sequelize";
import sequelize from "../config/db_sequelize.js";

const Malaria = sequelize.define("Malaria", {
  id: {
    type: DataTypes.STRING(24),
    primaryKey: true,
    allowNull: false,
  },
  governorate: DataTypes.STRING,
  wilayat: DataTypes.STRING,
  institution: DataTypes.STRING,
  reportingDate: DataTypes.DATE,
  patientId: DataTypes.STRING,
  civilId: DataTypes.STRING,
  expiryDate: DataTypes.DATE,
  age: DataTypes.INTEGER,
  firstName: DataTypes.STRING,
  secondName: DataTypes.STRING,
  dob: DataTypes.DATE,
  term: DataTypes.STRING,
  mobileNo: DataTypes.STRING,
  nextOfKinMobileNo: DataTypes.STRING,
  education: DataTypes.STRING,
  passportNo: DataTypes.STRING,
  placeOfWork: DataTypes.STRING,
  monthlyIncome: DataTypes.FLOAT,
  patientGovernorate: DataTypes.STRING,
  nationality: DataTypes.STRING,
  longitude: DataTypes.STRING,
  maritalStatus: DataTypes.STRING,
  patientWilayat: DataTypes.STRING,
  gender: DataTypes.STRING,
  workStatus: DataTypes.STRING,
  treatment: DataTypes.STRING,
  treatmentStartDate: DataTypes.DATE,
  treatmentDose: DataTypes.STRING,
  primaquine: DataTypes.STRING,
  outcome: DataTypes.STRING,
  outcomeDate: DataTypes.DATE,
  remarks: DataTypes.TEXT,
  dateOfOnset: DataTypes.DATE,
  symptoms: DataTypes.JSON, // Array
  pastHistoryOfMalaria: DataTypes.STRING,
  bloodTransfusionWithinPast3Months: DataTypes.STRING,
  rdtReportedDate: DataTypes.DATE,
  species: DataTypes.JSON, // Array
  density: DataTypes.STRING,
  stages: DataTypes.JSON, // Array
  parasiteCount: DataTypes.STRING,
  relapse: DataTypes.STRING,
  otherTreatment: DataTypes.STRING,
  otherTreatmentStartDate: DataTypes.DATE,
  treatmentEndDate: DataTypes.DATE,
  otherTreatmentDose: DataTypes.STRING,
  otherPrimaquine: DataTypes.STRING,
  otherOutcome: DataTypes.STRING,
  otherOutcomeDate: DataTypes.DATE,
  otherRemarks: DataTypes.TEXT,
  status: { type: DataTypes.STRING, defaultValue: "Pending" },
});

export default Malaria;
