import { DataTypes } from "sequelize";
import sequelize from "../config/db_sequelize.js";

const Polio = sequelize.define("Polio", {
  id: {
    type: DataTypes.STRING(24),
    primaryKey: true,
    allowNull: false,
  },
  governorate: DataTypes.STRING,
  wilayat: DataTypes.STRING,
  village: DataTypes.STRING,
  institution: DataTypes.STRING,
  patientId: DataTypes.STRING,
  civilId: DataTypes.STRING,
  expiryDate: DataTypes.DATE,
  dob: DataTypes.DATE,
  age: DataTypes.INTEGER,
  term: DataTypes.STRING,
  passportNo: DataTypes.STRING,
  nationality: DataTypes.STRING,
  firstName: DataTypes.STRING,
  secondName: DataTypes.STRING,
  thirdName: DataTypes.STRING,
  gender: DataTypes.STRING,
  tribe: DataTypes.STRING,
  sheikhName: DataTypes.STRING,
  mobileNo: DataTypes.STRING,
  nextOfKinMobileNo: DataTypes.STRING,
  maritalStatus: DataTypes.STRING,
  education: DataTypes.STRING,
  workStatus: DataTypes.STRING,
  occupations: DataTypes.STRING,
  placeOfWork: DataTypes.STRING,
  monthlyIncome: DataTypes.FLOAT,
  latitude: DataTypes.STRING,
  longitude: DataTypes.STRING,
  pidCase: DataTypes.STRING,
  familyHistory: DataTypes.STRING,
  dateOfFirstConsultation: DataTypes.DATE,
  dateOfConfirmation: DataTypes.DATE,
  ageAtDiagnosis: DataTypes.INTEGER,
  consanguinity: DataTypes.STRING,
  pidDiagnosis: DataTypes.STRING,
  travelOutsideOman: DataTypes.STRING,
  immunizationComplete: DataTypes.STRING,
  receivedIPV: DataTypes.STRING,
  receivedOPV: DataTypes.STRING,
  closeContactOPV: DataTypes.STRING,
  status: { type: DataTypes.STRING, defaultValue: "Pending" },
});

export default Polio;
